apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-101
  namespace: k8s-101
  labels:
    app: gitops-101
    env: dev
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gitops-101
      env: dev
  template:
    metadata:
      labels:
        app: gitops-101
        env: dev
    spec:
      containers:
        - name: gitops-101
          image: thanhtrdang/gitops-101:b20220106.0
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: gitops-101
  namespace: k8s-101
  labels:
    app: gitops-101
    env: dev
spec:
  selector:
    app: gitops-101
    env: dev
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gitops-101
  namespace: k8s-101
  annotations:
    konghq.com/strip-path: 'true'
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /api/v1/gitops-101
            pathType: ImplementationSpecific
            backend:
              service:
                name: gitops-101
                port:
                  number: 80
