apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitops-101
    env: dev
  name: gitops-101
  namespace: k8s-101
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: gitops-101
      env: dev
  template:
    metadata:
      labels:
        app: gitops-101
        env: dev
    spec:
      containers:
      - image: thanhtrdang/gitops-101:v1.0.1
        name: gitops-101
        ports:
        - containerPort: 3000
apiVersion: v1
kind: Service
metadata:
  labels:
    app: gitops-101
    env: dev
  name: gitops-101
  namespace: k8s-101
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: gitops-101
    env: dev
  template:
    spec:
      containers:
      - image: thanhtrdang/gitops-101:v1.0.1
        name: gitops-101
  type: ClusterIP
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    konghq.com/strip-path: "true"
  name: gitops-101
  namespace: k8s-101
spec:
  ingressClassName: kong
  rules:
  - http:
      paths:
      - backend:
          service:
            name: gitops-101
            port:
              number: 80
        path: /api/v1/gitops-101
        pathType: ImplementationSpecific
  template:
    spec:
      containers:
      - image: thanhtrdang/gitops-101:v1.0.1
        name: gitops-101
